export { change } from './changes.js';
export {
	isSyncError,
	normalizeSyncError,
	SyncError,
	syncError,
	syncErrorToHttpStatus,
	type SyncErrorCode,
	type SyncErrorOptions,
	type SyncRecoveryMetadata,
	type SyncRecoverySource
} from './errors.js';
export {
	encodeScope,
	manager,
	MemoryManagerOutbox,
	MemoryManagerRealtimeBus,
	type BoundManager,
	type Manager,
	type ManagerTypeFromResource,
	type ManagerWriteMethod
} from './manager.js';
export {
	andThen,
	err,
	isError,
	isOk,
	map,
	mapError,
	ok,
	Result,
	tryPromise,
	trySync,
	SyncErr,
	SyncOk,
	type InferErr,
	type InferOk,
	type SyncResult
} from '../shared/result.js';
export {
	resource,
	type AddMethodDefinition,
	type AddMethodInput,
	type AddResourceArgs,
	type AnyResourceMethodDefinition,
	type BatchResourceHandlerResult,
	type DeleteMethodDefinition,
	type DeleteMethodInput,
	type DeleteResourceArgs,
	type GetMethodDefinition,
	type GetMethodInput,
	type ListMethodDefinition,
	type ListMethodInput,
	type ListResourceArgs,
	type GetResourceArgs,
	type MethodBuilder,
	type MethodKind,
	type MutateMethodDefinition,
	type MutateMethodInput,
	type MutateResourceArgs,
	type Resource,
	type ResourceDefinition,
	type ResourceMethod,
	type ResourceMethodMap,
	type ResourceMethodType,
	type ResourceMethodTypes,
	type ResourceMethods,
	type ResourceWriteMethod
} from './resource.js';
export { createPubSubManagerRealtimeBus } from './realtime.js';
export type {
	ManagerRealtimeBusErrorContext,
	ManagerRealtimePubSubTransport,
	PubSubManagerRealtimeBusOptions
} from './realtime.js';
export {
	getRegisteredSharedStreamManagerKeys,
	getSharedStreamConfig,
	httpSharedSyncStream,
	publishSharedStreamEnvelope,
	registerSharedStreamManager,
	registerSharedStreamSubscription,
	resetSharedStreamForTests
} from './streamMultiplexer.js';
export { normalizeValidator, parseSchema } from './validator.js';
export type {
	AnySchema,
	AuthorizeHook,
	AuthorizeResult,
	Awaitable,
	CostMetric,
	InferSchemaOutput,
	ItemAddedChange,
	ItemDeletedChange,
	ItemUpdatedChange,
	ManagerHttpHandlerArgs,
	ManagerHttpHandlers,
	ManagerMutationRecord,
	ManagerMutationStatus,
	ManagerOutbox,
	ManagerOutboxRead,
	ManagerOptions,
	ManagerRealtimeBus,
	ManagerSyncPersistence,
	ManagerTelemetry,
	ManagerTelemetryContext,
	ManagerType,
	MethodType,
	OperationMeta,
	OperationOptions,
	PageLoadedChange,
	ResetChange,
	ResetManifest,
	ResourceCommit,
	ResourceCommitContext,
	ResourceCommitResult,
	ResourceExecution,
	ResourceHandlerContext,
	ResourceHandlerOk,
	ResourceHandlerResult,
	ResourceOk,
	ResourceOptions,
	ResourceSignalOk,
	ResourceStateOk,
	ResourceTelemetry,
	ResourceTelemetryContext,
	ScopeValue,
	StandardSchema,
	StandardSchemaValidationResult,
	SyncActor,
	SyncBatchErrorItem,
	SyncBatchExecution,
	SyncBatchItem,
	SyncBatchOkItem,
	SyncBatchOutput,
	SyncChange,
	SyncEnvelope,
	SyncHttpError,
	SyncHttpOk,
	SyncHttpResult,
	SyncSignal,
	Validator
} from './types.js';
